# Generated by Django 3.2.9 on 2022-05-11 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.rename


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=utils.rename.Rename.rename),
        ),
        migrations.AlterField(
            model_name='user',
            name='bg',
            field=models.ImageField(blank=True, null=True, upload_to=utils.rename.Rename.rename),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fontFamily',
            field=models.CharField(blank=True, choices=[['ABHAYA_LIBRE', 'ABHAYA_LIBRE'], ['ALLERTA_STENCIL', 'ALLERTA_STENCIL'], ['ANTON', 'ANTON'], ['BELLOTA_TEXT', 'BELLOTA_TEXT'], ['BLACK_OPS_ONE', 'BLACK_OPS_ONE'], ['CALLIGRAFFITTI', 'CALLIGRAFFITTI'], ['CHATHURA', 'CHATHURA'], ['CINZEL_DECORATIVE', 'CINZEL_DECORATIVE'], ['CODYSTAR', 'CODYSTAR'], ['FASTER_ONE', 'FASTER_ONE'], ['ICELAND', 'ICELAND'], ['KANIT', 'KANIT'], ['MODAK', 'MODAK'], ['MONOFETT', 'MONOFETT'], ['MONOTON', 'MONOTON'], ['NIXIE_ONE', 'NIXIE_ONE'], ['PINYON_SCRIPT', 'PINYON_SCRIPT'], ['PLASTER', 'PLASTER'], ['POIRET_ONE', 'POIRET_ONE'], ['RATIONALE', 'RATIONALE'], ['SAIRA_STENCIL_ONE', 'SAIRA_STENCIL_ONE'], ['STARDOS_STENCIL', 'STARDOS_STENCIL'], ['TEKO', 'TEKO']], default='ABHAYA_LIBRE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$tWLw5EfZ4fyG0yJghc9tGn$O5W4HsCxUWKjABw4qhw/wsGw+kJQJLU49uuzc5ESMQY=', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='personalPhone',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='resetPasswordDate',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='resetPasswordUUID',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uniqueId',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='welcome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='workPhone',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='workWebsite',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=utils.rename.Rename.rename),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_video', to=settings.AUTH_USER_MODEL),
        ),
    ]
