# Generated by Django 3.2.9 on 2022-05-11 10:56

import colorfield.fields
from django.db import migrations, models
import utils.rename


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Card', 'verbose_name_plural': 'Cards'},
        ),
        migrations.AlterField(
            model_name='card',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(upload_to=utils.rename.Rename.rename),
        ),
        migrations.AlterField(
            model_name='card',
            name='price_dirham',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='price_dollar',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='text_color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
